### ISSUE TITLE
problem in training 

### ISSUE THREAD

**Issue by meroluo** [HyeongseokSon1/SRFeat#8]
Thank you for your wonderful work！ Recently I want to train a model with my own datasets containing of some 3 channel images, but there exist a problem I can't deal with, hoping you can give me some suggestions. The error described as below:

 2019-02-27 19:12:13.209173: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-02-27 19:12:13.385843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:03:00.0
totalMemory: 7.93GiB freeMemory: 4.09GiB
2019-02-27 19:12:13.385884: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:03:00.0, compute capability: 6.1)
[*] Load checkpoint//g_SRFeat.npz SUCCESS!
Traceback (most recent call last):
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 3 and 0 for 'mean_squared_error_1/SquaredDifference' (op: 'SquaredDifference') with input shapes: [5,224,224,3], [0].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_gan_init.py", line 188, in <module>
    train()
  File "main_gan_init.py", line 103, in train
    val_mset = tl.cost.mean_squared_error(net_g_test.outputs , sample_imgs_384, is_mean=True)  
  File "/home/weihq/superresolution1/SRFeat-master/tensorlayer/cost.py", line 104, in mean_squared_error
    mse = tf.reduce_mean(tf.reduce_mean(tf.squared_difference(output, target), [1, 2, 3]))
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4601, in squared_difference
    "SquaredDifference", x=x, y=y, name=name)
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/weihq/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 3 and 0 for 'mean_squared_error_1/SquaredDifference' (op: 'SquaredDifference') with input shapes: [5,224,224,3], [0].

sincerely grateful for your reading!

**Comment by BeepBump** [comment]
Hi, I have the same problem, can u tell me how to solve it?

**Comment by HyeongseokSon1** [comment]
Sorry for late reply.
It seems that loading validation imgs fails.
As shown at line 60 and 61 in main_gan_init.py, the default code use bmp imgs as validation.
You can change the file extension appropriate for your validation set.
